# Generated by Django 4.2.6 on 2023-10-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('avatarURL', models.URLField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(choices=[('IND', 'India'), ('AUS', 'Australia'), ('ENG', 'England'), ('NZ', 'New Zealand'), ('SA', 'South Africa'), ('WI', 'West Indies'), ('PAK', 'Pakistan'), ('SL', 'Sri Lanka'), ('BAN', 'Bangladesh'), ('AFG', 'Afghanistan'), ('NED', 'Netherlands')], max_length=255)),
                ('iccId', models.IntegerField(blank=True, null=True)),
                ('howstatId', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Players',
                'db_table': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamCategory', models.CharField(choices=[('ICC', 'ICC'), ('IPL', 'IPL')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('flagURL', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'db_table': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('matchType', models.CharField(choices=[('ICC', 'ICC'), ('IPL', 'IPL')], max_length=255)),
                ('matchFormat', models.CharField(choices=[('ODI', 'ODI'), ('TEST', 'TEST'), ('T20', 'T20')], max_length=255)),
                ('matchNumber', models.IntegerField()),
                ('eventType', models.CharField(choices=[('SERIES', 'Series'), ('MATCH', 'Match')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('Playing11Team1PlayerId', models.ManyToManyField(related_name='playing11_team1', to='players.players')),
                ('Playing11Team2PlayerId', models.ManyToManyField(related_name='playing11_team2', to='players.players')),
                ('teamId1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='players.teams')),
                ('teamId2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='players.teams')),
            ],
            options={
                'verbose_name_plural': 'Upcoming Events',
                'db_table': 'UpcomingEvents',
            },
        ),
        migrations.CreateModel(
            name='ICCRanking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matchFormat', models.CharField(choices=[('ODI', 'ODI'), ('TEST', 'TEST'), ('T20', 'T20')], max_length=20)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('BOWLING', 'Bowling'), ('BATTING', 'Batting'), ('ALLROUNDER', 'All-Rounder')], max_length=20)),
                ('rank', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('playerId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
            options={
                'verbose_name_plural': 'ICC Rankings',
                'db_table': 'ICCRanking',
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('statsId', models.AutoField(primary_key=True, serialize=False)),
                ('matchType', models.CharField(choices=[('ODI', 'ODI'), ('T20', 'T20'), ('TEST', 'TEST')], max_length=4)),
                ('totalMatches', models.IntegerField()),
                ('innings', models.IntegerField()),
                ('notOuts', models.IntegerField()),
                ('aggregate', models.FloatField()),
                ('highestScore', models.CharField(max_length=255)),
                ('average', models.FloatField()),
                ('fiftys', models.IntegerField()),
                ('hundreds', models.IntegerField()),
                ('ducks', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('scoringRate', models.FloatField()),
                ('overs', models.FloatField()),
                ('runsConceded', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('bowlingAverage', models.FloatField()),
                ('bowlingEconomyRate', models.FloatField()),
                ('bowlingStrikeRate', models.FloatField()),
                ('playerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
            options={
                'verbose_name_plural': 'Player Stats',
                'db_table': 'PlayerStats',
                'unique_together': {('playerId', 'matchType')},
            },
        ),
    ]
