# Generated by Django 4.2.6 on 2023-11-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='ballsFaced',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingevents',
            name='cover',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
