# Generated by Django 4.2.6 on 2023-11-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_end_upcomingevents_startdatetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='matchType',
            new_name='matchFormat',
        ),
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together={('playerId', 'matchFormat')},
        ),
    ]
