# Generated by Django 4.2.6 on 2023-11-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_iccranking_playerid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iccranking',
            unique_together={('playerId', 'matchFormat', 'role')},
        ),
    ]
