# Generated by Django 4.2.6 on 2023-11-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_iccranking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iccranking',
            name='role',
            field=models.CharField(choices=[('BOWLING', 'Bowling'), ('BATTING', 'Batting'), ('ALL ROUNDER', 'All-Rounder')], max_length=20),
        ),
    ]
