# Generated by Django 4.2.6 on 2023-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_iccranking_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iccranking',
            name='role',
            field=models.CharField(choices=[('Bowler', 'Bowling'), ('Batsman', 'Batting'), ('All Rounder', 'All Rounder')], max_length=20),
        ),
    ]
