# Generated by Django 4.2.6 on 2023-11-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_alter_iccranking_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevents',
            name='playerOrderTeam1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upcomingevents',
            name='playerOrderTeam2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
