# Generated by Django 4.1.13 on 2023-12-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_upcomingevents_playerorderteam1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevents',
            name='BenchPlayersTeam1PlayerId',
            field=models.ManyToManyField(related_name='bench_players_team1', to='players.players'),
        ),
        migrations.AddField(
            model_name='upcomingevents',
            name='BenchPlayersTeam2PlayerId',
            field=models.ManyToManyField(related_name='bench_players_team2', to='players.players'),
        ),
    ]
