# Generated by Django 4.1.13 on 2024-03-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_upcomingevents_benchplayersteam1playerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerIPL',
            fields=[
                ('playerName', models.TextField()),
                ('playerTeamCode', models.TextField(choices=[('PBKS', 'PBKS'), ('DC', 'DC'), ('KKR', 'KKR'), ('sunrisers hyderabad', 'SRH'), ('chennai super kings', 'CSK'), ('royal challengers bengaluru', 'RCB'), ('rajasthan royals', 'RR'), ('lucknow super giants', 'LSG'), ('gujrat titans', 'GT'), ('mumbai indians', 'MI')])),
                ('playerIPLID', models.AutoField(primary_key=True, serialize=False)),
                ('battingMatchesPlayedPrev', models.IntegerField(null=True)),
                ('battingInningsPlayedPrev', models.IntegerField(null=True)),
                ('notOutPrev', models.IntegerField(null=True)),
                ('runsPrev', models.IntegerField(null=True)),
                ('highScorePrev', models.IntegerField(null=True)),
                ('averagePrev', models.IntegerField(null=True)),
                ('ballsFacedPrev', models.IntegerField(null=True)),
                ('strikeRatePrev', models.IntegerField(null=True)),
                ('bowlingMatchesPlayedPrev', models.IntegerField(null=True)),
                ('bowlingInningsPlayedPrev', models.IntegerField(null=True)),
                ('oversBowledPrev', models.IntegerField(null=True)),
                ('runsConceededPrev', models.IntegerField(null=True)),
                ('wicketsPrev', models.IntegerField(null=True)),
                ('bowlingAveragePrev', models.IntegerField(null=True)),
                ('economyPrev', models.IntegerField(null=True)),
                ('bowlingStrikeRatePrev', models.IntegerField(null=True)),
                ('battingMatchesPlayedCur', models.IntegerField(null=True)),
                ('battingInningsPlayedCur', models.IntegerField(null=True)),
                ('notOutCur', models.IntegerField(null=True)),
                ('runsCur', models.IntegerField(null=True)),
                ('highScoreCur', models.IntegerField(null=True)),
                ('averageCur', models.IntegerField(null=True)),
                ('ballsFacedCur', models.IntegerField(null=True)),
                ('strikeRateCur', models.IntegerField(null=True)),
                ('bowlingMatchesPlayedCur', models.IntegerField(null=True)),
                ('bowlingInningsPlayedCur', models.IntegerField(null=True)),
                ('oversBowledCur', models.IntegerField(null=True)),
                ('runsConceededCur', models.IntegerField(null=True)),
                ('wicketsCur', models.IntegerField(null=True)),
                ('bowlingAverageCur', models.FloatField(null=True)),
                ('economyCur', models.FloatField(null=True)),
                ('bowlingStrikeRateCur', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Player IPL',
                'db_table': 'PlayerIPL',
            },
        ),
    ]
