# Generated by Django 4.1.13 on 2024-04-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_playeripl_clientplayerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeripl',
            name='playerTeamCode',
            field=models.TextField(choices=[('PBKS', 'PBKS'), ('DC', 'DC'), ('KKR', 'KKR'), ('SRH', 'SRH'), ('CSK', 'CSK'), ('RCB', 'RCB'), ('RR', 'RR'), ('LSG', 'LSG'), ('GT', 'GT'), ('MI', 'MI')]),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='BenchPlayersTeam1PlayerId',
            field=models.ManyToManyField(related_name='bench_players_team1', to='players.playeripl'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='BenchPlayersTeam2PlayerId',
            field=models.ManyToManyField(related_name='bench_players_team2', to='players.playeripl'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='Playing11Team1PlayerId',
            field=models.ManyToManyField(related_name='playing11_team1', to='players.playeripl'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='Playing11Team2PlayerId',
            field=models.ManyToManyField(related_name='playing11_team2', to='players.playeripl'),
        ),
    ]
