# Generated by Django 4.1.13 on 2024-04-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_playeripl_playerrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeripl',
            name='imagePlayerId',
            field=models.IntegerField(null=True),
        ),
    ]
