# Generated by Django 4.2.6 on 2023-11-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePlayerStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playerICCId', models.IntegerField(blank=True, null=True)),
                ('playerHowstatId', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(choices=[('ODI', 'ODI'), ('TEST', 'TEST'), ('T20', 'T20')], max_length=20)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'UpdatePlayerStats',
                'db_table': 'UpdatePlayerStats',
            },
        ),
    ]
