# Generated by Django 4.2.6 on 2023-11-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateUpcomingEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matchUrl', models.CharField(max_length=255)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('matchType', models.CharField(choices=[('ICC', 'ICC'), ('IPL', 'IPL')], default='ICC', max_length=255)),
                ('matchFormat', models.CharField(choices=[('ODI', 'ODI'), ('TEST', 'TEST'), ('T20', 'T20')], max_length=255)),
                ('matchNumber', models.IntegerField(blank=True, null=True)),
                ('eventType', models.CharField(choices=[('SERIES', 'Series'), ('MATCH', 'Match')], default='Match', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'UpdateUpcomingEvents',
                'db_table': 'UpdateUpcomingEvents',
            },
        ),
        migrations.RenameField(
            model_name='updateplayerstats',
            old_name='playerHowstatId',
            new_name='howstatId',
        ),
        migrations.RenameField(
            model_name='updateplayerstats',
            old_name='playerICCId',
            new_name='iccId',
        ),
        migrations.RemoveField(
            model_name='updateplayerstats',
            name='format',
        ),
        migrations.AddField(
            model_name='updateplayerstats',
            name='matchFormat',
            field=models.CharField(choices=[('ODI', 'ODI'), ('TEST', 'TEST'), ('T20', 'T20'), ('ALL', 'ALL')], default='ALL', max_length=20),
        ),
    ]
